import { StyleSheet } from "react-native";

import {
  accountSheetCardTitle,
  accountSheetInputText,
  accountSheetPrimaryLabel,
  accountSheetSecondaryLabel,
} from "@/constants/accountSheetTypography";
import { rf, rs } from "@/utils/scale";

const HELP_FIELD_FOCUS = "#111111";

export const taxiAddressInputStyles = StyleSheet.create({
  routeRowWrap: { flex: 1, minWidth: 0, overflow: "visible" },
  routeRowPress: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: rs(6),
    flex: 1,
    minWidth: 0,
    paddingHorizontal: rs(14),
    paddingVertical: rs(10),
    minHeight: rs(52),
  },
  routeRowEditing: { borderRadius: rs(12) },
  routeRowBody: { gap: rs(6), minWidth: 0 },
  routeRowBodyGrow: { flex: 1, minWidth: 0, alignSelf: "stretch" },
  routeRowInput: {
    ...accountSheetPrimaryLabel,
    flex: 1,
    alignSelf: "stretch",
    width: "100%",
    padding: 0,
    margin: 0,
    minHeight: rs(28),
    fontSize: rf(16),
    fontFamily: "Inter_400Regular",
    lineHeight: rf(22),
  },
  routePreviewTrailing: { marginTop: rs(12), flexShrink: 0 },
  routeEditActionsInline: {
    flexDirection: "row",
    alignItems: "center",
    gap: rs(6),
    marginTop: rs(10),
    flexShrink: 0,
  },
  routeIconBtn: {
    width: rs(32),
    height: rs(32),
    borderRadius: rs(16),
    borderWidth: StyleSheet.hairlineWidth,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
  },
  routeIconBtnDone: { backgroundColor: HELP_FIELD_FOCUS, borderColor: HELP_FIELD_FOCUS },
  addressPreview: { flex: 1, gap: rs(2), justifyContent: "center" },
  routeAddressPreview: { flex: 1, gap: rs(2), justifyContent: "center", minWidth: 0 },
  routeAddressLine1: {
    fontSize: rf(15),
    fontFamily: "Inter_500Medium",
    lineHeight: rf(20),
  },
  routeAddressLine2: {
    fontSize: rf(13),
    fontFamily: "Inter_400Regular",
    lineHeight: rf(18),
  },
  inputText: { flex: 1, ...accountSheetInputText },
  liveGpsIconBtn: { padding: rs(4), flexShrink: 0 },
  liveResultGroup: { borderRadius: rs(14), borderWidth: 1.5, overflow: "hidden" },
  liveResultRow: { flexDirection: "row", alignItems: "center", gap: 12, padding: 14 },
  liveResultIcon: { width: 38, height: 38, borderRadius: 10, justifyContent: "center", alignItems: "center" },
  liveResultText: { flex: 1 },
  liveResultTitle: { fontSize: 15, fontFamily: "Inter_500Medium" },
  liveResultSub: { fontSize: 13, fontFamily: "Inter_400Regular", marginTop: 1 },
  liveResultDivider: { height: StyleSheet.hairlineWidth, marginLeft: 64 },
  liveSearchingRow: { flexDirection: "row", alignItems: "center", gap: 10, padding: 14 },
  liveSearchingText: { fontSize: 15, fontFamily: "Inter_400Regular" },
});

export const taxiRouteCardStyles = StyleSheet.create({
  routeAddressCard: {
    borderRadius: rs(16),
    borderWidth: 1.5,
    overflow: "visible",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: rs(2) },
    shadowOpacity: 0.06,
    shadowRadius: rs(8),
    elevation: 3,
  },
  fahrzielRoute: {
    flexDirection: "row",
    alignItems: "stretch",
  },
  fahrzielTimeline: {
    width: rs(32),
    alignItems: "center",
    paddingTop: rs(18),
    paddingBottom: rs(18),
    gap: rs(2),
    flexShrink: 0,
  },
  fahrzielDotOrigin: {
    width: rs(10),
    height: rs(10),
    borderRadius: rs(5),
    backgroundColor: "#222222",
    borderWidth: 2,
    borderColor: "#555555",
  },
  fahrzielConnector: {
    flex: 1,
    width: rs(2),
    borderRadius: rs(1),
    marginVertical: rs(3),
  },
  fahrzielDotDest: {
    width: rs(10),
    height: rs(10),
    borderRadius: rs(5),
  },
  fahrzielFieldsCol: {
    flex: 1,
    minWidth: 0,
    overflow: "visible",
    position: "relative",
  },
  fahrzielFieldSep: {
    height: rs(2),
    marginLeft: rs(8),
    marginRight: rs(8),
    opacity: 0.45,
  },
  dtField: {
    flexDirection: "row",
    alignItems: "center",
    gap: rs(10),
    borderRadius: rs(12),
    borderWidth: StyleSheet.hairlineWidth,
    paddingHorizontal: rs(14),
    paddingVertical: rs(14),
  },
  dtFieldText: { flex: 1, ...accountSheetPrimaryLabel },
  dtNote: accountSheetSecondaryLabel,
  infoBox: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: rs(8),
    padding: rs(12),
    borderRadius: rs(10),
    borderWidth: StyleSheet.hairlineWidth,
  },
  card: { borderRadius: rs(16), padding: rs(16), gap: rs(12) },
  sectionTitle: accountSheetCardTitle,
});
