import { Router, type IRouter } from "express";
import healthRouter from "./health";
import ridesRouter from "./rides";
import authRouter from "./auth";
import emailAuthRouter from "./emailAuth";
import customerAuthRouter from "./customerAuth";
import adminApiRouter from "./adminApi";
import adminFail2banRouter from "./adminFail2banRouter";
import adminServerStatusRouter from "./adminServerStatusRouter";
import panelAuthRouter from "./panelAuth";
import panelApiRouter from "./panelApi";
import panelInvoiceRoutesRouter from "./panelInvoiceRoutes";
import panelFixedPriceVoucherRoutesRouter from "./panelFixedPriceVoucherRoutes";
import panelKrankenInvoiceRoutesRouter from "./panelKrankenInvoiceRoutes";
import fleetAuthRouter from "./fleetAuth";
import fleetDriverApiRouter from "./fleetDriverApi";
import fleetPanelApiRouter from "./fleetPanelApi";
import companyOnboardingPanelRoutes from "./companyOnboardingPanelRoutes";
import insurerPanelApiRouter from "./insurerPanelApi";
import publicHomepageApiRouter from "./publicHomepageApi";
import publicAnalyticsApiRouter from "./publicAnalyticsApi";
import publicPlacesApiRouter from "./publicPlacesApi";
import appConfigApiRouter from "./appConfigApi";
import customerApiRouter from "./customerApi";

const router: IRouter = Router();

router.use(healthRouter);
router.use(appConfigApiRouter);
router.use(authRouter);
router.use(emailAuthRouter);
router.use(customerAuthRouter);
router.use(panelAuthRouter);
router.use(fleetAuthRouter);
router.use(fleetDriverApiRouter);
router.use(fleetPanelApiRouter);
router.use(companyOnboardingPanelRoutes);
router.use(insurerPanelApiRouter);
router.use(publicHomepageApiRouter);
router.use(publicAnalyticsApiRouter);
router.use(publicPlacesApiRouter);
router.use(panelApiRouter);
router.use(panelInvoiceRoutesRouter);
router.use(panelFixedPriceVoucherRoutesRouter);
router.use(panelKrankenInvoiceRoutesRouter);
router.use(adminApiRouter);
router.use(adminFail2banRouter);
router.use(adminServerStatusRouter);
router.use(customerApiRouter);
router.use(ridesRouter);

export default router;
