ALTER TABLE fare_areas
  ADD COLUMN IF NOT EXISTS is_default BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS base_fare_eur DOUBLE PRECISION NOT NULL DEFAULT 4.3,
  ADD COLUMN IF NOT EXISTS rate_first_km_eur DOUBLE PRECISION NOT NULL DEFAULT 3.0,
  ADD COLUMN IF NOT EXISTS rate_after_km_eur DOUBLE PRECISION NOT NULL DEFAULT 2.5,
  ADD COLUMN IF NOT EXISTS threshold_km DOUBLE PRECISION NOT NULL DEFAULT 4,
  ADD COLUMN IF NOT EXISTS waiting_per_hour_eur DOUBLE PRECISION NOT NULL DEFAULT 38,
  ADD COLUMN IF NOT EXISTS service_fee_eur DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS onroda_base_fare_eur DOUBLE PRECISION NOT NULL DEFAULT 3.5,
  ADD COLUMN IF NOT EXISTS onroda_per_km_eur DOUBLE PRECISION NOT NULL DEFAULT 2.2,
  ADD COLUMN IF NOT EXISTS onroda_min_fare_eur DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS manual_fixed_price_eur DOUBLE PRECISION;

UPDATE fare_areas
SET is_default = TRUE
WHERE id = (
  SELECT id
  FROM fare_areas
  ORDER BY id
  LIMIT 1
);
